/**
 * ZK Circuit Abstraction
 *
 * This module provides a structured interface for proving and verifying
 * AI-layer execution correctness in a way that is *agnostic to the underlying
 * proof system*. In production, the hash-based "prover" below would be
 * replaced by a real SNARK (e.g., Groth16, Plonk) or STARK backend.
 *
 * Architecture:
 *   - A circuit defines public inputs (spec, context) and private inputs (weights, activations).
 *   - A witness is generated by running the deterministic WASM inference.
 *   - A proof commits to the witness trace via deterministic hash commitments.
 *   - Verification re-computes the witness and checks Merkle openings.
 *
 * Swap-out points for real ZK:
 *   1. ZKSetup.generate()        -- replace with trusted-setup or universal-setup.
 *   2. ZKProver.prove()        -- replace with circuit-specific polynomial constraints.
 *   3. ZKVerifier.verify()     -- replace with pairing-product or FRI verification.
 */

import { sha256 } from '../wallet/crypto';
import { LayerSpec } from '../core/types';
import {
  wasmExecuteLayer,
  WasmRuntime,
  loadWasm,
  InferredExports,
  vector2Fixed,
  f2i,
} from '../wasm/runtime';
import {
  buildTraceRoot,
  commitLayerOutput,
  proveLayerOpening,
  verifyLayerOpening,
} from './index';
import { ExecutionContext } from './index';
import { Groth16Proof, proveLayer as groth16ProveLayer, verifyLayer as groth16VerifyLayer, computeTraceCommitmentHash } from './groth16';

// === Fixed-point helper for WASM ===
function floatToFixedArray(arr: number[]): number[] {
  return arr.map(v => Math.round(v * 65536));
}

// Deterministic fixed-point seed via SHA-256
function fixedSeedFloat(seedHex: string): number {
  const h = seedHex.substring(0, 8);
  const n = parseInt(h, 16);
  return (n % 65536) / 65536; // Q16.16 fraction
}

/**
 * Deterministic weights for a layer given architecture, task, and layer index.
 * In production, these would be the actual quantized model weights, loaded from
 * IPFS or a model registry. For the prototype, we deterministically generate
 * them so they are identical across every node.
 */
export function deriveLayerWeights(
  spec: LayerSpec,
  architecture: string,
  taskId: string,
  layerIndex: number
): { weights: number[]; bias: number[] } {
  const seed = sha256(`weights:${architecture}:${taskId}:${layerIndex}`);
  const inputSize = spec.inputShape.reduce((a, b) => a * b, 1);
  const outputSize = spec.outputShape.reduce((a, b) => a * b, 1);

  // Deterministic pseudo-random weights in range [-0.5, 0.5]
  const weights: number[] = [];
  const bias: number[] = [];
  for (let i = 0; i < inputSize * outputSize; i++) {
    const h = sha256(seed + ':' + i).substring(0, 8);
    const n = parseInt(h, 16);
    weights.push((n / 0x7fffffff) - 0.5);
  }
  for (let i = 0; i < outputSize; i++) {
    const h = sha256(seed + ':b:' + i).substring(0, 8);
    const n = parseInt(h, 16);
    bias.push((n / 0x7fffffff) * 0.1); // small bias
  }
  return { weights, bias };
}

// === Trace Commitment Builder ===

export interface TraceCommitment {
  layerIndex: number;
  opType: string;
  inputHash: string;
  outputHash: string;
  weightsHash: string;
  computationHash: string; // hash of WASM execution trace (simplified)
}

export function buildTraceCommitment(
  spec: LayerSpec,
  input: number[],
  output: number[],
  weights: number[],
  bias: number[]
): TraceCommitment {
  return {
    layerIndex: spec.index,
    opType: spec.opType,
    inputHash: sha256(JSON.stringify(input)),
    outputHash: sha256(JSON.stringify(output)),
    weightsHash: sha256(JSON.stringify(weights) + JSON.stringify(bias)),
    computationHash: sha256(
      JSON.stringify([
        spec.opType,
        spec.inputShape,
        spec.outputShape,
        input.length,
        output.length,
        weights.length,
      ])
    ),
  };
}

// === Layer Opening (Merkle Proof for a single layer) ===

export interface LayerMerkleProof {
  root: string;
  leafIndex: number;
  siblings: string[];
  layerCommitment: TraceCommitment;
}

function traceCommitmentToHash(tc: TraceCommitment): string {
  return sha256(JSON.stringify(tc));
}

function buildTraceMerkleRoot(traceCommitments: TraceCommitment[]): string {
  return buildTraceRoot(traceCommitments.map(traceCommitmentToHash));
}

function openTraceLayer(
  traceCommitments: TraceCommitment[],
  layerIndex: number
): LayerMerkleProof {
  const leafHashes = traceCommitments.map(traceCommitmentToHash);
  const mp = proveLayerOpening(leafHashes, layerIndex);
  return {
    root: buildTraceMerkleRoot(traceCommitments),
    leafIndex: mp.leafIndex,
    siblings: mp.siblings,
    layerCommitment: traceCommitments[layerIndex],
  };
}

function verifyTraceLayer(root: string, proof: LayerMerkleProof): boolean {
  return verifyLayerOpening(
    root,
    traceCommitmentToHash(proof.layerCommitment),
    { leafIndex: proof.leafIndex, siblings: proof.siblings }
  );
}

// === ZK Setup ===

export interface ZKSetup {
  provingKeyHash: string;
  verificationKeyHash: string;
}

export function generateSetup(architecture: string): ZKSetup {
  // PROTOTYPE: setup is just a hash commitment to the architecture spec.
  // In production this would be a trusted-setup ceremony output.
  return {
    provingKeyHash: sha256('pk:' + architecture),
    verificationKeyHash: sha256('vk:' + architecture),
  };
}

// === ZK Witness (WASM execution trace) ===

export interface ZKWitness {
  spec: LayerSpec;
  architecture: string;
  taskId: string;
  layerIndex: number;
  input: number[];
  weights: number[];
  bias: number[];
  output: number[];
  traceCommitment: TraceCommitment;
}

async function generateWitness(
  spec: LayerSpec,
  architecture: string,
  taskId: string,
  layerIndex: number,
  input: number[],
  weights: number[],
  bias: number[]
): Promise<ZKWitness> {
  const wasm = await loadWasm();
  const rt = new WasmRuntime(wasm);
  const output = rt.executeLayer(spec.opType, weights, input, bias);
  const traceCommitment = buildTraceCommitment(spec, input, output, weights, bias);
  return { spec, architecture, taskId, layerIndex, input, weights, bias, output, traceCommitment };
}

// === ZK Proof (hash-based for prototype, replaceable with SNARK) ===

export interface ZKProof {
  publicInputs: {
    architecture: string;
    taskId: string;
    layerIndex: number;
    specHash: string;
    traceRoot: string;
    outputHash: string;
  };
  witness: ZKWitness;             // in production this is private
  merkleProof: LayerMerkleProof;   // trace commitment opening
  snarkProof?: Groth16Proof;       // Groth16 SNARK (populated when available)
  snarkPublicSignals?: string[];  // Corresponding public signals
  setup: ZKSetup;
  /** Fallback hash-based signature used when Groth16 circuit is too small */
  proofSignature: string;
}

export async function prove(
  spec: LayerSpec,
  architecture: string,
  taskId: string,
  layerIndex: number,
  input: number[],
  weights: number[],
  bias: number[]
): Promise<ZKProof> {
  const witness = await generateWitness(spec, architecture, taskId, layerIndex, input, weights, bias);
  const setup = generateSetup(architecture);

  // Compute trace root (single layer)
  const traceCommitments = [witness.traceCommitment];
  const traceRoot = buildTraceMerkleRoot(traceCommitments);
  const merkleProof = openTraceLayer(traceCommitments, 0);

  // Attempt Groth16 SNARK proof for 4x4 layers
  let snarkProof: Groth16Proof | undefined;
  let snarkPublicSignals: string[] | undefined;
  let proofSignature: string;
  try {
    if (weights.length === 16 && bias.length === 4 && input.length === 4 && spec.outputShape.reduce((a, b) => a * b, 1) === 4) {
      const po = await groth16ProveLayer(input, weights, witness.output, bias);
      snarkProof = po.proof;
      snarkPublicSignals = po.publicSignals;
      proofSignature = sha256(JSON.stringify([setup.verificationKeyHash, traceRoot, witness.traceCommitment.outputHash, architecture, taskId, layerIndex, 'groth16']));
    } else {
      throw new Error('layer dimensions not supported by Groth16 circuit');
    }
  } catch (_e) {
    // Fallback: hash-based proof signature for unsupported dimensions
    proofSignature = sha256(
      JSON.stringify([
        setup.verificationKeyHash,
        traceRoot,
        witness.traceCommitment.outputHash,
        architecture,
        taskId,
        layerIndex,
      ])
    );
  }

  return {
    publicInputs: {
      architecture,
      taskId,
      layerIndex,
      specHash: sha256(JSON.stringify(spec)),
      traceRoot,
      outputHash: witness.traceCommitment.outputHash,
    },
    witness,
    merkleProof,
    snarkProof,
    snarkPublicSignals,
    setup,
    proofSignature,
  };
}

export async function verify(proof: ZKProof): Promise<boolean> {
  // 1. Recompute witness via deterministic WASM
  const recomputed = await generateWitness(
    proof.witness.spec,
    proof.publicInputs.architecture,
    proof.publicInputs.taskId,
    proof.publicInputs.layerIndex,
    proof.witness.input,
    proof.witness.weights,
    proof.witness.bias
  );

  // 2. Check output matches
  if (recomputed.traceCommitment.outputHash !== proof.publicInputs.outputHash) return false;

  // 3. Recompute trace root and verify Merkle opening
  const recomputedRoot = buildTraceMerkleRoot([recomputed.traceCommitment]);
  if (recomputedRoot !== proof.merkleProof.root) return false;
  if (!verifyTraceLayer(proof.merkleProof.root, proof.merkleProof)) return false;

  // 4. Verify Groth16 SNARK if present
  if (proof.snarkProof && proof.snarkPublicSignals) {
    const snarkOk = await groth16VerifyLayer(proof.snarkProof, proof.snarkPublicSignals);
    if (!snarkOk) return false;
  }

  // 5. Fallback: check proof signature integrity
  const groth16Suffix = proof.snarkProof ? 'groth16' : undefined;
  const sigParts = [
    proof.setup.verificationKeyHash,
    proof.merkleProof.root,
    proof.publicInputs.outputHash,
    proof.publicInputs.architecture,
    proof.publicInputs.taskId,
    proof.publicInputs.layerIndex,
  ];
  if (groth16Suffix) sigParts.push(groth16Suffix);

  const expectedSig = sha256(JSON.stringify(sigParts));
  if (expectedSig !== proof.proofSignature) return false;

  // 6. Check setup consistency
  const expectedSetup = generateSetup(proof.publicInputs.architecture);
  if (expectedSetup.verificationKeyHash !== proof.setup.verificationKeyHash) return false;

  return true;
}

// === Full Model ZK Proof ===

export interface ModelZKProof {
  architecture: string;
  taskId: string;
  traceRoot: string;
  layerProofs: ZKProof[];
  setup: ZKSetup;
}

export async function proveModel(
  architecture: string,
  taskId: string,
  layerSpecs: LayerSpec[],
  allWeights: number[][],   // per-layer
  allBiases: number[][],   // per-layer
  initialInput: number[]
): Promise<ModelZKProof> {
  const setup = generateSetup(architecture);
  const layerProofs: ZKProof[] = [];
  let currentInput = initialInput;

  for (let i = 0; i < layerSpecs.length; i++) {
    const proof = await prove(
      layerSpecs[i],
      architecture,
      taskId,
      i,
      currentInput,
      allWeights[i],
      allBiases[i]
    );
    layerProofs.push(proof);
    currentInput = proof.witness.output;
  }

  // Full trace root over all layer trace commitment hashes
  const traceCommitments = layerProofs.map(p => p.witness.traceCommitment);
  const traceRoot = buildTraceMerkleRoot(traceCommitments);

  return { architecture, taskId, traceRoot, layerProofs, setup };
}

export async function verifyModel(modelProof: ModelZKProof): Promise<boolean> {
  // Verify every layer proof
  for (const lp of modelProof.layerProofs) {
    if (!(await verify(lp))) return false;
  }
  // Rebuild trace root
  const traceCommitments = modelProof.layerProofs.map(p => p.witness.traceCommitment);
  const recomputedRoot = buildTraceMerkleRoot(traceCommitments);
  if (recomputedRoot !== modelProof.traceRoot) return false;
  return true;
}
